config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView


urlpatterns = [
    # New index (React-based):
    path('', TemplateView.as_view(template_name="index.html"), name='home'),
    # Old index:
    # path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    path('movies/', include('moviesapp.movies.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

moviesapp/movies/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from rest_framework.authtoken import views as token_views
from . import views

app_name = 'movies'

urlpatterns = [
    path('', view=views.MovieListView.as_view(), name='index'),
    path('<int:id>/', view=views.MovieRetrieveUpdateView.as_view(), name='detail'),
    path('create/', view=views.MovieCreateView.as_view(), name='create'),
    path('update/<int:id>/', view=views.MovieRetrieveUpdateView.as_view(), name='update'),
    path('delete/<int:id>/', view=views.MovieDeleteView.as_view(), name='delete'),
    path('<int:movie_id>/vote/', views.vote, name='vote'),
    path('auth/', token_views.obtain_auth_token),
]

moviesapp/movies/models.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Movie(models.Model):
    title = models.CharField(_('Movie\'s title'), max_length=255, unique=True)
    year = models.PositiveIntegerField(default=2020)
    # Example: PG-13
    rated = models.CharField(max_length=64)
    released_on = models.DateField(_('Release Date'))
    genre = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    plot = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False) 

    class Meta:
        ordering = ["-released_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'id': self.pk})

class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    STARS = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5')
    ]
    rating_number = models.CharField(max_length=1, choices=STARS, default='1')

moviesapp/movies/forms.py
from django import forms
from .models import Movie

class MovieModelForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'year', 'rated', 'released_on', 'genre', 'director', 'plot']

moviesapp/movies/views.py
# -*- coding: utf-8 -*-

"""Movies views."""

# from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
import json
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg, Count
from django.db.models.functions import Coalesce

# API
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveUpdateAPIView, DestroyAPIView
from .serializers import *

from .models import Movie, Rating
# from .forms import MovieModelForm

class MovieListView(SuccessMessageMixin, ListAPIView):
    """Show all movies."""
    queryset = Movie.objects.annotate(num_votes=Count('rating'), avg_rating=Coalesce(Avg('rating__rating_number'), 0))
    #context_object_name = 'movie_list'
    serializer_class = MovieSerializer

class MovieCreateView(SuccessMessageMixin, CreateAPIView):
    """Create a new movie."""
    serializer_class = MovieSerializer
    success_message = "The movie created successfully"
    def create(self, request, *args, **kwargs):
        response = super().create(request, *args, **kwargs)
        return Response({
            'status': 200,
            'message': 'The movie created successfully',
            'data': response.data
        })

class MovieRetrieveUpdateView(SuccessMessageMixin, RetrieveUpdateAPIView):
    """Show the requested movie."""
    model = Movie
    context_object_name = 'movie'
    serializer_class = MovieSerializer
    success_message = "The movie updated successfully"
    def get(self, request, *args, **kwargs):
        try:
            return super(MovieRetrieveUpdateView, self).get(request, *args, **kwargs)
        except Http404:
            return redirect('/')
    def get_object(self):
        return get_object_or_404(Movie, **self.kwargs)

class MovieDeleteView(DestroyAPIView):
    """Delete the requested movie."""
    model = Movie
    serializer_class = MovieSerializer
    success_url = '/movies'
    def get(self, request, *args, **kwargs):
        try:
            return super(MovieDeleteView, self).get(request, *args, **kwargs)
        except Http404:
            return redirect('/movies')
    def get_object(self):
        return get_object_or_404(Movie, **self.kwargs)
    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, 'The movie deleted successfully')
        return response

def vote(request, movie_id):
    body = json.loads(request.body)
    rating = body['rating']
    rating = Rating(movie_id=movie_id, rating_number=rating)
    rating.save()
    messages.success(request, 'Your vote was recorded successfully')
    return HttpResponseRedirect(reverse('movies:index'))

moviesapp/templates/403_csrf.html
{% extends 'base.html' %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

moviesapp/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans 'MoviesCRUDApp' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block css %}
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block javascript %}
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <script src="js/html5shiv.min.js"></script>
      <![endif]-->
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/scalar-logo.png' %}" width="200" alt="Scalar"/></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
            <li class="active"><a href="{% url 'movies:index' %}">{% trans 'Movies' %}</a></li>
            <li class="active"><a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">

      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <p class="msg msg-{{ message.tags }}">{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}{% endblock %}

        <hr>
        <footer>
            <p>&copy; 2005 - {% now 'Y' %} {% blocktrans %}At Scalar, we love going to the movies (especially if it is a new release). We are film critics and use this web app to add our reviews and comments.{% endblocktrans %}</p>
        </footer>

    </div> <!-- /container -->

    {% block modal %}{% endblock %}

    {% block scripts %}{% endblock %}

  </body>
</html>


{% comment %}
  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">MoviesCRUDApp</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'movies:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
{% endcomment %}

moviesapp/templates/movies/movie_confirm_delete.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{% trans
'Movie' %}: {% trans 'Delete' %}{% endblock %} {% block content %}

<h1>{{ object.title }}</h1>

<form
  class="form-horizontal"
  method="post"
  action="{% url 'movies:delete' object.pk %}"
>
  {% csrf_token %}
  {{ form.as_p }}
  <p>{% trans 'Are you sure you want to delete the movie?' %}</p>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% trans 'Yes, delete' %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

moviesapp/templates/movies/movie_detail.html
{% extends 'base.html' %} 
{% load static i18n %} 
{% block title %}
  {{ movie.title }}
{% endblock %} 
{% block content %}
<h3>{{ movie.title }}</h3>
<div class="row">
  <div class="col-sm-12">
    <dl>
      <dd><strong>Year:</strong> {{ movie.year }}</dd>
      <dd><strong>Rated:</strong> {{ movie.rated }}</dd>
      <dd><strong>Released on:</strong> {{ movie.released_on }}</dd>
      <dd><strong>Genre:</strong> {{ movie.genre }}</dd>
      <dd><strong>Director:</strong> {{ movie.director }}</dd>
      <dd><strong>Plot:</strong> {{ movie.plot }}</dd>
      <dd><strong>Created at:</strong> {{ movie.created_at }}</dd>
      <dd><strong>Updated at:</strong> {{ movie.updated_at }}</dd>
    </dl>
  </div>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <form action="{% url 'movies:vote' movie.id %}" method="post">
    {% csrf_token %}
    <input type="radio" name="rating" id="star1" value="1">
    <label for="star1">1 star</label><br>
    <input type="radio" name="rating" id="star2" value="2">
    <label for="star2">2 stars</label><br>
    <input type="radio" name="rating" id="star3" value="3">
    <label for="star3">3 stars</label><br>
    <input type="radio" name="rating" id="star4" value="4">
    <label for="star4">4 stars</label><br>
    <input type="radio" name="rating" id="star5" value="5">
    <label for="star5">5 stars</label><br>
    <input type="submit" value="Vote">
  </form>
</div>
{% endblock %}

moviesapp/templates/movies/movie_form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Movie' %}{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>


<form class="form-horizontal" method="post" 
{% if 'create' in request.path %}
  action="{% url 'movies:create' %}"
{% else %}
  action="{% url 'movies:update' object.pk %}"
{% endif %}>
  {% csrf_token %}
  {{ form.as_p }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% if 'create' in request.path %}{% trans 'Create' %}{% else %}{% trans 'Update' %}{% endif %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

moviesapp/templates/movies/movie_list.html
{% extends 'base.html' %} 
{% load static i18n %} 
{% block title %}
  {% trans 'Movies' %}
{% endblock %} 
{% block content %}
<h3>{% trans 'Movies' %}</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Released on</th>
      <th>Votes</th>
      <th>Stars</th>
      <th colspan="2" class="text-center"><strong>Action</strong></th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movie_list %}
    <tr>
      <td>
        <a href="{{ movie.get_absolute_url }}">{{ movie.pk }}</a>
      </td>
      <td>{{ movie.title }}</td>
      <td>{{ movie.released_on }}</td>
      <td>{{ movie.num_votes }}</td>
      <td>{{ movie.avg_rating }}</td>
      <td class="text-center"><a href="{% url 'movies:update' movie.pk %}">Edit</a></td>
      <td class="text-center"><a href="{% url 'movies:delete' movie.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="6"><a href="{% url 'movies:create' %}">Add new movie</a></td>
    </tr>
  </tbody>
</table>
{% endblock content %}

moviesapp/templates/pages/home.html
{% extends 'base.html' %} {% load static i18n %}

<div class="jumbotron">
  <h1>{% blocktrans %}Welcome to Django Framework{% endblocktrans %}</h1>
  <p>
    {% blocktrans %}Congratulations! You have successfully installed the Movies
    CRUD App. You are currently running Django Framework.{% endblocktrans %}
  </p>
  <p>
    <a
      class="btn btn-success btn-lg"
      href="https://github.com/django/django"
      target="_blank"
      >{% blocktrans %}Fork Django on GitHub{% endblocktrans %} &raquo;</a
    >
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Follow Development{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          {% blocktrans %}Django is under active development...{% endblocktrans %}
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Discover Modules{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>{% blocktrans %}The community is working on...{% endblocktrans %}</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Help &amp; Support{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          {% blocktrans %}If you need any help or support while developing with
          Django, you may reach us via...{% endblocktrans %}
        </p>
      </div>
    </div>
  </div>
</div>